version: "3"

services:
  node-todo:
    image: a1qkt/node-todo:v0.0.12
    ports:
      - 3000:3000
    volumes:
      - ./:/node-todo
    deploy:
  #     replicas: 3
      restart_policy:
        condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017 
    volumes: 
      - ./database:/data/db
    # deploy: 
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M


