version: "3.7"

services:
  node-todo:
    build: .
    image: a1qkt/node-todo:v0.0.1
    ports:
      - 3000:3000
    container_name: test1
    volumes:
      - ./:/node-todo

  mongodb:
    image: mongo
    container_name: mongo-test1
    environment:
      - PUID=1000 
      - PGID=1000 
    ports:
      - 27017:27017 
    volumes: 
      - ./database:/data/db
    restart: unless-stopped